apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-service-dp
  labels:
    app: trips-service
  namespace: staging-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips-service
  template:
    metadata:
      labels:
        app: trips-service
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z trips-service-db-srv 3306; do echo waiting for db; sleep 2; done']
      containers:
        - name: trips-service
          image: docker.io/rvanappeldorn/trips-service:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DB_USER
              valueFrom:
                secretKeyRef: { name: trips-db-credentials, key: user }
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef: { name: trips-db-credentials, key: password }
            - name: DATABASE_URL
              value: mariadb+pymysql://$(DB_USER):$(DB_PASSWORD)@trips-service-db-srv.$(POD_NAMESPACE).svc.cluster.local:3306/accounts?charset=utf8mb4
            - name: SERVER_NAME
              value: trips-service
          ports:
            - containerPort: 80
